* Negation
** Position of nicht(not) and nei(mals) never
*** Negative follows :
**** Adverbs of *Specific Time*  *after*
***** Ich komme heute nicht mit
      I am not coming with you today

***** Wir wollen es diese Woche nicht machen
      We don't want to do it this week.

**** *except* adverbs of *general time*
     such as : immer,oft,selten
***** Er ist nicht immer so faul gewesen
      He has not always been so lazy
**** *definite* direct objects:
***** Negative follows direct objtects
***** Ich habe ({das/dieses/sein} Buch) nicht finden koenen(definite)

      I have not been able to find
      the/this/that/his book.

***** Er hat (sie) nicht getroffen (definite pronominal object)

      He didn't meet her

***** Kennst du (ihn) nicht? (definite pronominal)

      Don't you know him?

**** *except* *indefinite* direct objects:
     Negation is preceding the *indefinite* direct object
     where indefinteness is marked by {ein/eine}
***** Er hat nei (ein Buch) gelesen

      He has never read a buch

***** Ich habe nei -> (eine wirklich gute Schere) kaufen koenen

      I have never been able to buy a good pair of scissors





*** Negative precedes
**** *indefinte* direct objects (*do*)

     Negative precedes direct object as long as it is
     indefinte noun preceded by: (ein) or (viel) or
     indefinte pronoun: like {etwas,jemand, niemand}

***** Er hat nei <- (ein) Auto gehabt

      He's never had a car

***** Wir werden nicht <- (viel/viele) Sachen mit dem Geld kaufen

      We won't be able to buy much/many things with money

**** Adverbial expressions eg.

***** Ich fahre nicht mit dem Zug, (sondern mit dem Auto)
      I am not going by train (but by car).

***** Sie will nicht alleine zum Arzt gehen

      She does not want to go to the doctor on her own

**** Adverbial Expression of place:
***** Ich wohne nicht im achten Stock
      I don't live on the eighth floor
***** Sie ist nie in England gewesen
      She has never been to England
***** Er hat nicht im Gerten gearbeitet
      He hasn't been working in the garden

**** Prepositional Objects:
***** Hast du nei -> (von ihm) gehoert ?
      Have you never heard of him?
***** Ich haette neimals -> (an so was) gedacht
      I would never have thought of such a thing
***** Ich habe noch nicht -> (an meine Nichte) geschrieben
      I haven't written to my niece yet

**** Predicative(???) Adjectives:
***** Die Fensterscheibe ist nicht ->(kaputt)
      The window pane isn't broken
***** Ich bin nicht ->(bloed)
      I am not stupid

**** Any word or phrase which is specifically negated,

***** (Wir) wollen (es) nicht -> (diese Woche machen) (sondern naechste Woche)

***** (Er) hat (im Garten) nicht gearbeitet, sondenr gespielt

      He wasn't working in the garden (but playing) 

***** Nicht -> (der Kanzler hat (das gesagt))

*** Notes on negatives 

**** 'Not...a/any' or 'no + nount' are translated to kein

***** Ich habe kein Auto (nicht ein not possible here) 

      I don't have a car./ I have no car

***** Er gibt kein Geld aus.

      He doesn't spend any money/ He spends no money.

      The combination of nicht..ein is possible when ein
      is stressed meaing 'not a/one single'

***** Wir sind vier Wochen in Suedafrika gewesen und haben nicht eine Loewen gesehen.

      We were in South Africa for four weeks and 
      did not see one lion.

***** Wir sind vier Wochen in Suedafrica gewesen und haben keinen einzigen Loewen gesehen.
      
      We were in South africa for four weeks and did not see a single 
      lion.

  
**** 'Not one' is 'nicht ein'  or keiner

*****  Nicht einer meiner Freunde hat mich besucht als ich krank war.
       
       Not one of my friends visited me when I was sick.

***** Keiner meiner Freunde hat mich besucht asl ich krank war.

      None of my friends visited me when I was sick.

****  Further usage

***** Diese Tiere fressen kein Gras

      These animals don't eat grass 

***** Gras fressen diese Tiere nicht

***** Es waren keine normalen Katzen.
      
      They were not/no ordinary cats.

***** Er kann/spricht kein Deutsch

      H doesn't know (not any) German/ H can't speak any German.

***** Ich habe keine Eile.

      I am not in a hurry.

***** Ich habe keinen Hunger.

      I am not hungry

**** 'No(t)...at all' is rendered by either gar nicht/kein or ueberhaupt

***** Ich hatte gar nicht daran gedacht. Ich hatte ueberhaupt nicht daran gadacht.

      I hadn't thought of it at all

***** Ich habe gar kein Aut./Ich habe ueberhaupt kein Autho

      I haven't got a car at all

***** Er hat gar kein Geld./Er hat ueberhaupt kein Geld.

      He ahs no money at all.

**** 'Not...until' is translated *erst* (never *nicht...bis*) 

***** Er kommt erst morgen

      He is not coming until tomorrow/
      He is only coming tomorrow.

***** Sie kommen erst naechsten Montag

      They are not coming until next Monday.


***** Erst dann wird's passieren.

      Only then/Not till then will it happen.


**** 'Not...either' is translated simply by 'auch nicht/kein'

     Nie, but never neimals, is also very frequently used
     in combination with nocht.

***** Ich gehe auch nicht

      I am not going either.

***** Sie hat auch keins

      She has not got one either. (i.e car, neuter acc.)


**** 'Not...yet' is translated by noch nicht. e.g

***** Das neue Krankenhaus ist noch nict eroeffnet worden.

      The new hospital hasn't been opened yet.

***** Er hat (noch) nei ein Versprechen eingehalten

      He is never (yet) kept a promise.

***** Die Regierung wird dieses Gesetz nei verabschieden

      The government will never pass this law.

**** Note the following affirmative/negative couplets:

     {etwas - somthing }   / {nichts - nothing}
     {irgendwo- somewhere} / {nirgendwo - nowhere}
     {jemand  - someone}   / {neimand - no-one nobody}
     {je(mals) - ever }    / {nei(mals) - never} 


**** When contradicting a negative quesiton 'yes' is rendered by doch not *ja*


***** A: Du bist nicht nerheiratent, oder? B: (Doch)

      You are not married are you ? B: Yes, (I am )

***** Aber er hat's nicht alleine geschafft, (nicht wahr)?
      
      But he didn't manage it on his own, did he?

***** Er fliegt morgen nach Japan, (nicht wahr)?

      He is flying to Japan, isn't he ? 

***** Du bist um sechs wieder da, gell/nicht/ne?

      You'll be back here at six won't you?


      Also commonly heard spoken in Germn is oder?

**** Even is usually rendered by sogar while 'not even' is 'nicht einmal'

***** Sogar er ist mitgekommen

      Even he came along

***** Sien Name wurde nicht einmal erwaehnt

      His name wasn't even mentioned.


      


      


     
      

      

