
* Prepositions
  
  Most idiomatic parts of speech.
  Propositions can govern case. 

  {Nouns/Pronouns} following prepositions must follow
  case of {accusative, dative, gentive}

  Two-way prepositions an be accusative or dative.

  
** Prepositions that take accusative case
   
   eith prepositions require any following noun
   to be in accusative case: 

   FUDGEBOW - will accuse you 
   Fuer , Um, Durch, Gegen, Entlag, Bis, Ohne, Wider

*** bis (until, by, as far as)
    up to a certain (time/place)

***** Er belibt bis naechste Woche
     He is staying till next week.
***** Bis morgen
     See you tomorrow.
***** Ich will das Buch bitte bis naechste Woche zurueck haben
     I want to have a book back by next week, please.
***** Bis wann muss ich wieder heir sein?
     By when must I be back here?
***** Ich fahre nur bis Hannover.
     I am only going as far as Hanover.
***** von Kopf bis Fuz
     from head to toe

***** von oben bis unten
     from top to bottom



**** If used with a determiner in between there must be second governing proposition

***** Es muss (bis) zum Jahr 2015 eine Loesung gefunden werden.
      
      By 2015 asolution has to be found.
***** Wir werden (bis in) das naechste Jahrhundert eine Loesung suchen.

      We will be searchign for a solutino till next century.

***** Das Wasser kam (bis an) seinen mund

      The water came (up until) as far as his mouth.

***** Er ging (bis an) den Zaun und nicht wieter.

      He walked as far as the fence and no furhter.

*** durch (through by)
**** The primary meaning is through.

***** Wir sind quer (durch) die Mitte der Stadt gefahren.
      We drove straight through the center of the town. 

***** Ich habe es (durch) Zufall gehoert
      I heard it through/by chance.

**** Can also be rendered 'by ' in pasive when non person

***** Die Gastaette is (durch) Feuer zerstoert worden
      The restaurant was destroyed by fire.

*** entlang (along)

**** Sie gingen den Fluss(acc.) (entlang)
     They walked along the river.

**** Sie gingen am(an+dative) Fluss entlang.
     They walked along the river.

*** fuer (for)

***** Ich habe ein Geschenk fuer dich(acc.)

     I have a gift for you 

***** Wie viel hast du dafuer bezahlt?

     How much did you pay for it?

*** gegen(against)

***** Stell die Lieter gegen die Wand!

      Put the ladder (up) against the wall

***** Ich habe nichts gegen ihn

      I have nothing against him

***** Er kam so gegen acht Uhr an.

      He arrived at about eight o'clock (lit. getting on towards eight. but no later)

***** Er tauchten ploetzlich gegen fuenfzig Kinder auf.

      All of a sudden about fifty children turned up.

*** ohne (without)

**** Never followed by an indefinite article

***** Nur er war ohne Schlips    
      Only he was without a tie

***** Er geht nei ohne seinen Hund spazieren
      He never goes for a walk without his dog.

**** Ohne is also used as a conjunction.

*** um (around)
**** The primary meaning of um is 'around'

***** Ich bin zweimal umdie Welt geflogen
      I have flown around the world twice.

***** Der Film faengt um halb acht an.
      
      The film starts at half past seven.
      
*** wider(against)

    Formal synonemn for gegen



** Prepositions that take the *Dative Case*

   Mneumonic:'out of from midnight , tight by  xtwo
              'aus ,von,  mit,nach   seit, bei,zu'
   
*** aus (out of,from)
**** The primary meaning of aus is out of 
*** Er rannte aus-> (dem Huas) (dative.)
    He ran out of th house.
*** Ich komme aus Frankreich/Paris
    I came from France/Paris
*** Der Brief kam aus Poeln
    The letter was from Poland

*** auzer (apart from, except for, besides, other than)
**** Context depedendent translation from above option list.
**** Idiomatic out of may be auzer not aus .
***** Das Telefon an der Ecke ist auzer(out of) Betreib
      The telphone on the corner is out of order.
***** Sie war auzer sich (vor Angst)
      She was besides herself (wiht fear).

***** Ich musste rennen und war deswegen voellig auzer(without) Atem.
      I had to run and was thus completely out of breath.

*** bei(at, with)
**** many idiomatic uses, at.. and with
***** Dieses Jahr feiern wir meinen Guburtstag bei meinen, Grozeltern

***** Meine Fruendin wohnt noch bei ihern Elern..

      My girlfriend is still living with her parents.
**** Used with definitive article with professional places

***** Meine Frau ist beim Arzt
      My wife is at the doctor's 

***** Ich bin ihr beim Baeker begegnet 
      I bumped into her at the bakers'/ in the bakery

**** When you state that you baught s.t at a particular shop

***** Ich habe unseren neuen Fernseher bei Hertie gekauft.
      
      I bought our new television set at Harrods'

***** Mein  Onken arbeitet bei VW.

      My uncle works for VW.

**** Reflexive pronoun "on one'sperson"

***** Er hatte keinen Pfenning bei sich

      He didn't have a penny on him

***** Beim Fahren hat man Zeit ueber Gott und die Welt nachzudenken
      
      You have time to think about everyhting under the sun when you'r
      driving.

*** gegenueber( opposite, towards)

***** Er saz mir gegenueber
      He sat opposite me.

***** Er wohnt der alten Damen gegenueber
      He lives opposite me.
      
***** Die Baekerei befindet sich gegenueber dem Postamt.

      The bakery is situated opposite the post office.

*** mit (with)      

***** Er gign mit seinem Hund im Park spazieren

      He went for a walk with his dog in the park.

***** Mit diesem Messer kann man kein Brot schneidn.
***** Sie ist mit der Strazenbahn in die Stadt gefahren

*** nach (to, after)
**** The most usual meaning of nack is 'after'
**** 

*** seit (since, for)
*** von (from, off, of)
*** zu (to)
*** ab (from)



* Negation
** Position of nicht(not) and nei(mals) never
*** Negative follows :
**** Adverbs of *Specific Time*  *after*
***** Ich komme heute nicht mit
      I am not coming with you today

***** Wir wollen es diese Woche nicht machen
      We don't want to do it this week.

**** *except* adverbs of *general time*
     such as : immer,oft,selten
***** Er ist nicht immer so faul gewesen
      He has not always been so lazy
**** *definite* direct objects:
***** Negative follows direct objtects
***** Ich habe ({das/dieses/sein} Buch) nicht finden koenen(definite)

      I have not been able to find
      the/this/that/his book.

***** Er hat (sie) nicht getroffen (definite pronominal object)

      He didn't meet her

***** Kennst du (ihn) nicht? (definite pronominal)

      Don't you know him?

**** *except* *indefinite* direct objects:
     Negation is preceding the *indefinite* direct object
     where indefinteness is marked by {ein/eine}
***** Er hat nei (ein Buch) gelesen

      He has never read a buch

***** Ich habe nei -> (eine wirklich gute Schere) kaufen koenen

      I have never been able to buy a good pair of scissors





*** Negative precedes
**** *indefinte* direct objects (*do*)

     Negative precedes direct object as long as it is
     indefinte noun preceded by: (ein) or (viel) or
     indefinte pronoun: like {etwas,jemand, niemand}

***** Er hat nei <- (ein) Auto gehabt

      He's never had a car

***** Wir werden nicht <- (viel/viele) Sachen mit dem Geld kaufen

      We won't be able to buy much/many things with money

**** Adverbial expressions eg.

***** Ich fahre nicht mit dem Zug, (sondern mit dem Auto)
      I am not going by train (but by car).

***** Sie will nicht alleine zum Arzt gehen

      She does not want to go to the doctor on her own

**** Adverbial Expression of place:
***** Ich wohne nicht im achten Stock
      I don't live on the eighth floor
***** Sie ist nie in England gewesen
      She has never been to England
***** Er hat nicht im Gerten gearbeitet
      He hasn't been working in the garden

**** Prepositional Objects:
***** Hast du nei -> (von ihm) gehoert ?
      Have you never heard of him?
***** Ich haette neimals -> (an so was) gedacht
      I would never have thought of such a thing
***** Ich habe noch nicht -> (an meine Nichte) geschrieben
      I haven't written to my niece yet

**** Predicative(???) Adjectives:
***** Die Fensterscheibe ist nicht ->(kaputt)
      The window pane isn't broken
***** Ich bin nicht ->(bloed)
      I am not stupid

**** Any word or phrase which is specifically negated,

***** (Wir) wollen (es) nicht -> (diese Woche machen) (sondern naechste Woche)

***** (Er) hat (im Garten) nicht gearbeitet, sondenr gespielt

      He wasn't working in the garden (but playing) 

***** Nicht -> (der Kanzler hat (das gesagt))

*** Notes on negatives 

**** 'Not...a/any' or 'no + nount' are translated to kein

***** Ich habe kein Auto (nicht ein not possible here) 

      I don't have a car./ I have no car

***** Er gibt kein Geld aus.

      He doesn't spend any money/ He spends no money.

      The combination of nicht..ein is possible when ein
      is stressed meaing 'not a/one single'

***** Wir sind vier Wochen in Suedafrika gewesen und haben nicht eine Loewen gesehen.

      We were in South Africa for four weeks and 
      did not see one lion.

***** Wir sind vier Wochen in Suedafrica gewesen und haben keinen einzigen Loewen gesehen.
      
      We were in South africa for four weeks and did not see a single 
      lion.

  
**** 'Not one' is 'nicht ein'  or keiner

*****  Nicht einer meiner Freunde hat mich besucht als ich krank war.
       
       Not one of my friends visited me when I was sick.

***** Keiner meiner Freunde hat mich besucht asl ich krank war.

      None of my friends visited me when I was sick.

****  Further usage

***** Diese Tiere fressen kein Gras

      These animals don't eat grass 

***** Gras fressen diese Tiere nicht

***** Es waren keine normalen Katzen.
      
      They were not/no ordinary cats.

***** Er kann/spricht kein Deutsch

      H doesn't know (not any) German/ H can't speak any German.

***** Ich habe keine Eile.

      I am not in a hurry.

***** Ich habe keinen Hunger.

      I am not hungry

**** 'No(t)...at all' is rendered by either gar nicht/kein or ueberhaupt

***** Ich hatte gar nicht daran gedacht. Ich hatte ueberhaupt nicht daran gadacht.

      I hadn't thought of it at all

***** Ich habe gar kein Aut./Ich habe ueberhaupt kein Autho

      I haven't got a car at all

***** Er hat gar kein Geld./Er hat ueberhaupt kein Geld.

      He ahs no money at all.

**** 'Not...until' is translated *erst* (never *nicht...bis*) 

***** Er kommt erst morgen

      He is not coming until tomorrow/
      He is only coming tomorrow.

***** Sie kommen erst naechsten Montag

      They are not coming until next Monday.


***** Erst dann wird's passieren.

      Only then/Not till then will it happen.


**** 'Not...either' is translated simply by 'auch nicht/kein'

     Nie, but never neimals, is also very frequently used
     in combination with nocht.

***** Ich gehe auch nicht

      I am not going either.

***** Sie hat auch keins

      She has not got one either. (i.e car, neuter acc.)


**** 'Not...yet' is translated by noch nicht. e.g

***** Das neue Krankenhaus ist noch nict eroeffnet worden.

      The new hospital hasn't been opened yet.

***** Er hat (noch) nei ein Versprechen eingehalten

      He is never (yet) kept a promise.

***** Die Regierung wird dieses Gesetz nei verabschieden

      The government will never pass this law.

**** Note the following affirmative/negative couplets:

     {etwas - somthing }   / {nichts - nothing}
     {irgendwo- somewhere} / {nirgendwo - nowhere}
     {jemand  - someone}   / {neimand - no-one nobody}
     {je(mals) - ever }    / {nei(mals) - never} 


**** When contradicting a negative quesiton 'yes' is rendered by doch not *ja*


***** A: Du bist nicht nerheiratent, oder? B: (Doch)

      You are not married are you ? B: Yes, (I am )

***** Aber er hat's nicht alleine geschafft, (nicht wahr)?
      
      But he didn't manage it on his own, did he?

***** Er fliegt morgen nach Japan, (nicht wahr)?

      He is flying to Japan, isn't he ? 

***** Du bist um sechs wieder da, gell/nicht/ne?

      You'll be back here at six won't you?


      Also commonly heard spoken in Germn is oder?

**** Even is usually rendered by sogar while 'not even' is 'nicht einmal'

***** Sogar er ist mitgekommen

      Even he came along

***** Sien Name wurde nicht einmal erwaehnt

      His name wasn't even mentioned.


      


      


     
      

      

